### ISSUE TITLE
Blocks missing the prep_id meta data in testbed

### ISSUE THREAD

**Issue by amaltaro** [dmwm/dbs2go#25]
Valentin, it looks like the testbed Go-based DBSWriter is failing to insert the `prep_id` block attribute. I see the same pattern in many test workflows that I have been running over the past days.

An example is:
amaltaro_ReReco_RunBlockWhite_Agent202_Val_220412_035330_7983

which gives me the following information when retrieving information from DBS (you can also see some block names):
```
    /HLTPhysicsIsolatedBunch/Run2016H-ReReco_RunBlockWhite_Agent202_Val_Alanv8-v11/AOD: 
        /HLTPhysicsIsolatedBunch/Run2016H-ReReco_RunBlockWhite_Agent202_Val_Alanv8-v11/AOD#6ced57e5-88b2-4a2e-9590-b5e3a99a11a7: 
            PNN: T2_CH_CERN
            isOpen: 0
            numFiles: 1
        dsetSize: 2030976678
        events: 3008
        lumis: 3
        numBlocks: 1
        numFiles: 1
        prep_id: None
        release: CMSSW_8_0_23
    /HLTPhysicsIsolatedBunch/Run2016H-ReReco_RunBlockWhite_Agent202_Val_Alanv8-v11/DQMIO: 
        /HLTPhysicsIsolatedBunch/Run2016H-ReReco_RunBlockWhite_Agent202_Val_Alanv8-v11/DQMIO#349459f4-a8c9-48d4-9cb4-b32179105baf: 
            PNN: T2_CH_CERN
            isOpen: 0
            numFiles: 1
        dsetSize: 18308771
        events: 0
        lumis: 3
        numBlocks: 1
        numFiles: 1
        prep_id: None
        release: CMSSW_8_0_23
    /HLTPhysicsIsolatedBunch/Run2016H-ReReco_RunBlockWhite_Agent202_Val_Alanv8-v11/MINIAOD: 
        /HLTPhysicsIsolatedBunch/Run2016H-ReReco_RunBlockWhite_Agent202_Val_Alanv8-v11/MINIAOD#bfc67a46-6ab4-41b2-850b-4cd3b1ffdb2d: 
            PNN: T2_CH_CERN
            isOpen: 0
            numFiles: 1
        dsetSize: 151814182
        events: 3008
        lumis: 3
        numBlocks: 1
        numFiles: 1
        prep_id: None
        release: CMSSW_8_0_23
```

Can you look into the logs to see what the problem is? If you need a block dump, then I'd have to setup another test, which takes some effort but can be done.

**Comment by vkuznet** [comment]
@amaltaro I need to know the input JSON, there are two possibilities here:
- either prep_id had a wrong data-type (string vs integer) which was provided within input JSON, or
- DBSWriter needs to find prep_id based on information provided in JSON and somehow it fails
In either case I need an input to do the internal test and debug the issue (by default input HTTP POST payload is not dumped into the log since it can be very huge in size as you well aware).

**Comment by amaltaro** [comment]
That's going to take a while then. Nonetheless, prep_id is definitely not an integer. At the request level, this is one example:
```
  "PrepID": "TEST-ReReco-Run2016H-v1-09Nov2016-0016",
```

**Comment by vkuznet** [comment]
ok, that's good to know. Just tell me which API(s) was used to insert the data and then I can start looking into the code and try on my own to inject some data.

**Comment by amaltaro** [comment]
it's always the same client API, this: https://github.com/dmwm/WMCore/blob/1.5.7_wmagent/src/python/WMComponent/DBS3Buffer/DBSUploadPoller.py#L85

Valentin, to save you some time as well, I found this OLD block dump made by WMAgent, many years ago when I was talking to Yuyi:
https://amaltaro.web.cern.ch/amaltaro/forYuyi/dbsuploader_block.json

you can use it as a reference to your tests (note though that prep_id was null for this dump).

**Comment by vkuznet** [comment]
I found the problem, indeed, it was missing in bulkblocks API, the change is committed through this 6c4220e7257f76ab55226b36d25e6d568204fe3a commit and it is deployed on testbed. Please try again to insert new block and report the outcome. I'm performing DBS integration test now too.

**Comment by vkuznet** [comment]
@amaltaro did you get chance to run more injections and verify if issue is gone?

**Comment by amaltaro** [comment]
Hi @vkuznet , yes, it seems to be working fine now. Here are a few fresh blocks from the last 24h:
```
    /HLTPhysicsIsolatedBunch/Run2016H-ReReco_RunBlockWhite_Agent202_Val_Alanv9-v11/AOD: 
        /HLTPhysicsIsolatedBunch/Run2016H-ReReco_RunBlockWhite_Agent202_Val_Alanv9-v11/AOD#0d13bcd3-a546-49f7-b5d4-e7079788f86e: 
            PNN: T1_US_FNAL_Disk
            isOpen: 0
            numFiles: 1
        dsetSize: 1345304728
        events: 1654
        lumis: 1
        numBlocks: 1
        numFiles: 1
        prep_id: TEST-ReReco-Run2016H-v1-09Nov2016-0016
        release: CMSSW_8_0_23
    /HLTPhysicsIsolatedBunch/Run2016H-ReReco_RunBlockWhite_Agent202_Val_Alanv9-v11/DQMIO: 
        /HLTPhysicsIsolatedBunch/Run2016H-ReReco_RunBlockWhite_Agent202_Val_Alanv9-v11/DQMIO#2dd2af1e-6aa0-4953-b582-cbbe1eff28cf: 
            PNN: T1_US_FNAL_Disk
            isOpen: 0
            numFiles: 1
        dsetSize: 17210254
        events: 0
        lumis: 1
        numBlocks: 1
        numFiles: 1
        prep_id: TEST-ReReco-Run2016H-v1-09Nov2016-0016
        release: CMSSW_8_0_23
```

Thank you for the prompt fix. Feel free to close this issue.
